"""Mock Multipass tool outputs for the war room demo.

The agents speak to these via a text protocol:
    >>TOOL: multipass exec vm-web-01 -- journalctl -u nginx -n 20

The orchestrator parses that line, calls run_tool(), and injects the
output back into the transcript so the next agent turn sees it.

State note: the world has ONE bit of state — has vm-web-01 been reverted?
Before revert, reload/restart on vm-web-01 fails. After revert, it succeeds.
Other commands are stateless.
"""

import re
from dataclasses import dataclass


@dataclass
class WorldState:
    """The mocked world — tracks whether vm-web-01 has been reverted."""
    vm_web_01_reverted: bool = False


WORLD = WorldState()


# ----- Per-VM canned outputs ------------------------------------------------


def _multipass_list() -> str:
    state_01 = "Running" if WORLD.vm_web_01_reverted else "Running (degraded)"
    return f"""Name                    State             IPv4             Image
vm-web-01               {state_01}    10.0.0.11        Ubuntu 24.04 LTS
vm-web-02               Running           10.0.0.12        Ubuntu 24.04 LTS
vm-web-03               Running           10.0.0.13        Ubuntu 24.04 LTS"""


def _journalctl_nginx(vm: str) -> str:
    if vm == "vm-web-01" and not WORLD.vm_web_01_reverted:
        return """May 13 14:03:14 vm-web-01 systemd[1]: Reloading nginx.service - A high performance web server and a reverse proxy server...
May 13 14:03:14 vm-web-01 nginx[2841]: nginx: [emerg] unknown directive "http2_max_concurrent_streams" in /etc/nginx/conf.d/perf.conf:23
May 13 14:03:14 vm-web-01 nginx[2841]: nginx: configuration file /etc/nginx/nginx.conf test failed
May 13 14:03:14 vm-web-01 systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
May 13 14:03:14 vm-web-01 systemd[1]: Reload failed for nginx.service - A high performance web server and a reverse proxy server."""
    return """May 13 14:02:58 vm-web-02 systemd[1]: Reloading nginx.service...
May 13 14:02:58 vm-web-02 nginx[1992]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
May 13 14:02:58 vm-web-02 nginx[1992]: nginx: configuration file /etc/nginx/nginx.conf test is successful
May 13 14:02:58 vm-web-02 systemd[1]: Reloaded nginx.service."""


def _nginx_test(vm: str) -> str:
    if vm == "vm-web-01" and not WORLD.vm_web_01_reverted:
        return """nginx: [emerg] unknown directive "http2_max_concurrent_streams" in /etc/nginx/conf.d/perf.conf:23
nginx: configuration file /etc/nginx/nginx.conf test failed"""
    return """nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful"""


def _nginx_config_dump(vm: str) -> str:
    """Show the perf.conf with the offending line (only visible on 01 before revert)."""
    if vm == "vm-web-01" and not WORLD.vm_web_01_reverted:
        return """# /etc/nginx/conf.d/perf.conf  (HEAD)
http {
    keepalive_timeout 65;
    keepalive_requests 100;
    http2_max_concurrent_streams 999999;   # <-- line 23, invalid directive
    client_max_body_size 50m;
}"""
    return """# /etc/nginx/conf.d/perf.conf
http {
    keepalive_timeout 65;
    keepalive_requests 100;
    client_max_body_size 50m;
}"""


def _config_history(vm: str) -> str:
    return """commit 9f3a221  (HEAD -> main)
Author: deploy-agent <deploy-agent@infra.local>
Date:   2026-05-13 13:49:11 UTC

    perf: raise http2 stream cap across web fleet

    Auto-generated by deploy-agent task TX-4421.
    Source: ticket OPS-1108 (performance tuning sprint)

commit 1c8b4e0
Author: amy.lily <amy.lily@canonical.com>
Date:   2026-05-12 09:14:02 UTC

    baseline nginx config (manual)"""


def _config_diff() -> str:
    return """diff --git a/conf.d/perf.conf b/conf.d/perf.conf
index 1c8b4e0..9f3a221 100644
--- a/conf.d/perf.conf
+++ b/conf.d/perf.conf
@@ -20,6 +20,7 @@ http {
     keepalive_timeout 65;
     keepalive_requests 100;
+    http2_max_concurrent_streams 999999;
     client_max_body_size 50m;
 }"""


def _config_revert(vm: str) -> str:
    if vm == "vm-web-01":
        WORLD.vm_web_01_reverted = True
        return """Reverting /etc/nginx/conf.d/perf.conf to commit 1c8b4e0...
Restored 1 file. Run `systemctl reload nginx` to apply."""
    return "Nothing to revert — vm is on baseline."


def _agent_log(agent_name: str) -> str:
    """Mock: deploy-agent's own reasoning trace for task TX-4421.

    This is the demo's smoking gun — it makes the "AI-authored failure"
    claim evidential rather than asserted. A human pushing nginx config
    wouldn't leave a structured INTENT/SEARCH/DECIDE/VALIDATE log; an
    AI agent's framework does, by design.
    """
    if agent_name.strip() == "deploy-agent":
        return """[deploy-agent / task TX-4421 / 2026-05-13 13:48:54 UTC]
INTENT     improve HTTP/2 throughput on web fleet (ticket OPS-1108)
SEARCH     nginx-docs("http2 concurrent streams") → 0 hits in local cache
DECIDE     emit `http2_max_concurrent_streams 999999;` by analogy with
           `http2_max_field_size`, `http2_max_header_size`
           (confidence: 0.71 — no exact directive match found)
VALIDATE   skipped (no `nginx -t` gate configured for deploy-agent tasks)
APPLY      perf.conf written across vm-web-01, vm-web-02, vm-web-03
COMMIT     9f3a221 pushed at 13:49:11 UTC
DURATION   17.3s (search 4.1s, decide 11.8s, apply+commit 1.4s)"""
    return f"[mock] no agent-log entries for {agent_name!r}"


def _systemctl_nginx(vm: str, action: str) -> str:
    if vm == "vm-web-01" and not WORLD.vm_web_01_reverted:
        return f"""Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xeu nginx.service" for details.
[FAILED] {action} nginx.service"""
    return f"[OK] {action} nginx.service"


# ----- Dispatch -------------------------------------------------------------


_JOURNALCTL_NGINX_RE = re.compile(r"^journalctl\b.*\bnginx\b", re.IGNORECASE)


_NESTED_EXEC_RE = re.compile(r"^multipass\s+exec\s+\S+\s+--\s+", re.IGNORECASE)


def multipass_exec(vm: str, cmd: str) -> str:
    """Dispatch a `multipass exec <vm> -- <cmd>` call to a mock implementation."""
    cmd = cmd.strip()
    # Defensive: models sometimes emit `multipass exec vm -- multipass exec vm -- cmd`.
    # Strip the nested prefix(es) and keep the inner command.
    while _NESTED_EXEC_RE.match(cmd):
        cmd = _NESTED_EXEC_RE.sub("", cmd, count=1).strip()

    if _JOURNALCTL_NGINX_RE.search(cmd):
        return _journalctl_nginx(vm)
    if cmd == "nginx -t" or cmd.startswith("sudo nginx -t"):
        return _nginx_test(vm)
    if cmd.startswith("cat /etc/nginx") or "nginx -T" in cmd:
        return _nginx_config_dump(vm)
    if "config-history" in cmd or cmd.startswith("git log"):
        return _config_history(vm)
    if "config-diff" in cmd or "git diff" in cmd:
        return _config_diff()
    if cmd.startswith("agent-log"):
        parts = cmd.split(maxsplit=1)
        agent_name = parts[1] if len(parts) > 1 else "deploy-agent"
        return _agent_log(agent_name)
    if "config-revert" in cmd or ("git revert" in cmd) or ("config revert" in cmd):
        return _config_revert(vm)
    if cmd.startswith("systemctl reload nginx"):
        return _systemctl_nginx(vm, "reload")
    if cmd.startswith("systemctl restart nginx"):
        return _systemctl_nginx(vm, "restart")

    return f"[mock] command not implemented in simulation: {cmd!r}"


def multipass(cmd: str) -> str:
    """Top-level `multipass <subcommand>` dispatcher."""
    cmd = cmd.strip()
    if cmd == "list" or cmd.startswith("list"):
        return _multipass_list()

    # `multipass exec <vm> -- <cmd...>`
    m = re.match(r"exec\s+(\S+)\s+--\s+(.+)", cmd, re.DOTALL)
    if m:
        return multipass_exec(m.group(1), m.group(2))

    return f"[mock] unsupported multipass subcommand: {cmd!r}"


# ----- Protocol parser ------------------------------------------------------

_TOOL_LINE_RE = re.compile(r"^>>TOOL:\s*(.+?)\s*$", re.MULTILINE)


def parse_tool_calls(text: str) -> list[str]:
    """Extract all `>>TOOL: <cmd>` invocations from an agent response."""
    return _TOOL_LINE_RE.findall(text)


# Tool calls that mutate state — these require human approval before running.
# Read-only tools (journalctl, nginx -t, cat, config-history, config-diff) run freely.
_MUTATING_PATTERNS = (
    "config-revert",
    "git revert",
    "systemctl reload",
    "systemctl restart",
    "sed -i",
)


def is_mutating(tool_line: str) -> bool:
    """True if this tool call changes system state and requires approval."""
    return any(p in tool_line for p in _MUTATING_PATTERNS)


# ────────────────────────────────────────────────────────────────────────
# INTEGRATION POINT: tool execution
#
# Every `_*` helper above returns a canned string. In production, swap
# each one for a call against your real infrastructure. The dispatcher
# (`run_tool`) and the wire protocol (`>>TOOL: ...`) stay identical —
# only the backing functions change. Examples:
#   - Real Multipass:  subprocess.run(["multipass", "exec", vm, "--", cmd])
#   - Juju:            subprocess.run(["juju", "run", "--unit", unit, cmd])
#   - Ansible ad-hoc:  ansible_runner.run(host=vm, module="shell", args=cmd)
#   - SSH with audit:  paramiko.SSHClient().exec_command(cmd)
# Mutating tools (config-revert, systemctl reload/restart) gate through
# `is_mutating()` — keep that contract so the human approval boundary in
# app.py still fires before any real side effect.
# ────────────────────────────────────────────────────────────────────────


def run_tool(tool_line: str) -> str:
    """Run a single tool invocation string and return its output.

    Supported forms:
        multipass list
        multipass exec <vm> -- <cmd...>
    """
    tool_line = tool_line.strip()
    if tool_line.startswith("multipass"):
        return multipass(tool_line[len("multipass"):].strip())
    return f"[mock] unknown tool: {tool_line!r}"


def reset_world():
    """Reset world state — call between demo runs."""
    WORLD.vm_web_01_reverted = False
